name: Run IT Internship Finder

on:
  schedule:
    # Run every 2 hours (GitHub Actions uses UTC)
    - cron: "0 */2 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Cache seen URLs
        uses: actions/cache@v3
        with:
          path: seen_urls.json
          key: ${{ runner.os }}-seen-urls-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-seen-urls-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: |
          python main.py
          
      - name: Commit and push seen URLs
        if: success()
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add seen_urls.json
          git commit -m "Update seen URLs [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: internship_finder.log
